# Config file for raspy2mqtt (A.k.a. "ha-alarm-raspy2mqtt")
# Written by Francesco Montorsi, Feb 2024.

mqtt:
  broker: 192.168.1.5

# sampling frequency for the input
sampling_frequency_msec: 1000

# inputs are those provided by the Sequent Microsystem 16ch-optoinsulated board
inputs:
  # the MQTT topic will be in the form "home-assistant/<input name>"
  - name: opto_input_1
    input_num: 1
    normally_closed: true

# outputs are produced using the SeenGreat 2ch optoinsulated board
outputs:
  - name: ext_alarm_siren
    gpio: 20
  - name: int_alarm_siren
    gpio: 21
