[project]
name = "ha-alarm-raspy2mqtt"
version = "0.0.1"
authors = [
  { name="Francesco Montorsi", email="francesco.montorsi@gmail.com" },
]
description = ""
readme = "README.md"
# some features like asyncio TaskGroups and Exception groups are available only since Python 3.11:
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

# reference docs:
#  aiomqtt ->    https://sbtinstruments.github.io/aiomqtt/
#  SM16inpind -> https://github.com/SequentMicrosystems/16inpind-rpi/tree/main/python
#  PyYAML ->     https://pyyaml.org/wiki/PyYAMLDocumentation
#  gpiozero ->   https://gpiozero.readthedocs.io/en/latest/index.html
#  DEPRECATED: RPi.GPIO ->   https://pythonhosted.org/RPIO/   (backend for gpiozero)
#              As of March 2024, RPI.GPIO does not work anymore on latest Raspbian, see https://github.com/gpiozero/gpiozero/issues/1136
#              So I had to switch to pigpio, which however needs a daemon to be running to work (!!!)
dependencies = [
  "aiomqtt>=2.0.0",
  "SM16inpind>=1.0.1",
  "PyYAML",
  "gpiozero",
  "pigpio>=1.78"
]

[project.urls]
"Homepage" = "https://github.com/f18m/ha-alarm-raspy2mqtt"
"Bug Tracker" = "https://github.com/f18m/ha-alarm-raspy2mqtt/issues"

[project.scripts]
raspy2mqtt = "raspy2mqtt:main_loop"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
  "raspy2mqtt/*.py"
]

[tool.hatch.build.targets.wheel]
packages = ["raspy2mqtt"]

[tool.black]
line-length = 120