name: main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install pypi-packaged dependencies
      run: sudo pip3 install build

    # test Python packaging
    - name: package the pypi
      run: |
        python3 -m build

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install pypi-packaged dependencies
      run: sudo pip3 install black
    - name: lint the code
      run: black .

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install pypi-packaged dependencies for unit and integration tests
      run: sudo pip3 install pytest testcontainers paho-mqtt

    - name: run unit tests
      run: pytest -vvv -m unit
    - name: run integration tests
      run: pytest -vvv --capture=no -m integration
